### ISSUE TITLE
DAS5 update

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/cerise-mdstudio-das5#18]
CUDA has been updated breaking the current gromacs installation

**Comment by LourensVeen** [comment]
Ah right, because we're uploading binaries, right? Hmm. Having the install script compile is also not great though, takes a long time.

**Comment by felipeZ** [comment]
Actually the CUDA drivers has changed and probably we need to recompile. There is also another issue with the intel compiler. I'm waiting for the answer of the DAS5 administrators

**Comment by felipeZ** [comment]
The CUDA75 libraries has been eliminated. I will try to recompile using CUDA90

**Comment by LourensVeen** [comment]
I'm pretty sure I used GCC, not sure if Intel will be faster but it's worth a try I guess. Here are some notes I took when compiling Gromacs on DAS, maybe useful?

```
[lveen@fs0 ~]$ cd gromacs/
[lveen@fs0 gromacs]$ wget 'http://ftp.gromacs.org/pub/gromacs/gromacs-2016.tar.gz'
[lveen@fs0 gromacs]$ tar xf gromacs-2016.tar.gz
[lveen@fs0 gromacs]$ cd gromacs-2016/
[lveen@fs0 gromacs-2016]$ mkdir build
[lveen@fs0 gromacs-2016]$ cd build
[lveen@fs0 build]$ module load fftw3/openmpi/gcc/64/3.3.4
[lveen@fs0 build]$ module load cuda75/blas/7.5.18
[lveen@fs0 build]$ module load cuda75/fft/7.5.18
[lveen@fs0 build]$ module load cuda75/gdk/352.79
[lveen@fs0 build]$ module load cuda75/toolkit/7.5.18
[lveen@fs0 build]$ module load openmpi/gcc/64/1.10.1
[lveen@fs0 build]$ ccmake ..

Hit 'c' to configure
CMAKE_INSTALL_PREFIX=/home/lveen/opt/gromacs5
GMX_MPI=ON (will disable THREAD_MPI, but that's ok)
GMX_DEFAULT_SUFFIX=OFF
Hit 'c' to configure again, and another 'c' to enable generation
Hit 'g' to generate

[lveen@fs0 build]$ make -j 8
[lveen@fs0 build]$ make install
[lveen@fs0 build]$ . ~/opt/gromacs5/bin/GMXRC.bash
```
You'll need to tweak the directories at least I guess, and IIRC the GXMRC.bash it installs has hard coded paths in it, so you may have to adjust those to point to $HOME/.cerise/... instead of whichever prefix you used when compiling. And use $HOME, because it'll be in the user's home dir, not in yours :).

**Comment by felipeZ** [comment]
Thanks for the script and the hints!
We can not used the intel compilers due to [this issue](https://stackoverflow.com/questions/41727220/error-with-intel-c-compiler-identifier-compare-is-undefined), therefore I'm using GCC and CUDA90.
