### ISSUE TITLE
service not found

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/cerise-mdstudio-das5#3]
I'm creating a service with the `require_managed_service` function, subsequently I call the `service_to_dict` function and store the result as  a json file that looks like:
```
{"name": "cerise-mdstudio-das5-myuser", "port": 29593}
```
Then, when I try to use the `service_from_dict` method I get the following error:
```
  File "MDStudio/venv/local/lib/python2.7/site-packages/cerise_client/service.py", line 229, in service_from_dict
    return get_managed_service(srv_dict['name'], srv_dict['port'])
  File "MDStudio/venv/local/lib/python2.7/site-packages/cerise_client/service.py", line 120, in get_managed_service
    raise errors.ServiceNotFound()
cerise_client.errors.ServiceNotFound: 

```

**Comment by LourensVeen** [comment]
Hmm, does the cerise-mdstudio-das5-myuser Docker container still exist?

**Comment by felipeZ** [comment]
My fault, I was doing something wrong with the remote process!
